// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: shared/v1/pockets.proto

package sharedv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/matfire/pockets/shared/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PocketsServiceName is the fully-qualified name of the PocketsService service.
	PocketsServiceName = "shared.v1.PocketsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PocketsServiceGetContainersProcedure is the fully-qualified name of the PocketsService's
	// GetContainers RPC.
	PocketsServiceGetContainersProcedure = "/shared.v1.PocketsService/GetContainers"
	// PocketsServiceCreateContainerProcedure is the fully-qualified name of the PocketsService's
	// CreateContainer RPC.
	PocketsServiceCreateContainerProcedure = "/shared.v1.PocketsService/CreateContainer"
	// PocketsServiceCheckImageProcedure is the fully-qualified name of the PocketsService's CheckImage
	// RPC.
	PocketsServiceCheckImageProcedure = "/shared.v1.PocketsService/CheckImage"
	// PocketsServiceCreateImageProcedure is the fully-qualified name of the PocketsService's
	// CreateImage RPC.
	PocketsServiceCreateImageProcedure = "/shared.v1.PocketsService/CreateImage"
	// PocketsServiceStartContainerProcedure is the fully-qualified name of the PocketsService's
	// StartContainer RPC.
	PocketsServiceStartContainerProcedure = "/shared.v1.PocketsService/StartContainer"
	// PocketsServiceStopContainerProcedure is the fully-qualified name of the PocketsService's
	// StopContainer RPC.
	PocketsServiceStopContainerProcedure = "/shared.v1.PocketsService/StopContainer"
	// PocketsServiceDeleteContainerProcedure is the fully-qualified name of the PocketsService's
	// DeleteContainer RPC.
	PocketsServiceDeleteContainerProcedure = "/shared.v1.PocketsService/DeleteContainer"

)

// PocketsServiceClient is a client for the shared.v1.PocketsService service.
type PocketsServiceClient interface {
	GetContainers(context.Context, *connect.Request[v1.GetContainersRequest]) (*connect.Response[v1.GetContainersResponse], error)
	CreateContainer(context.Context, *connect.Request[v1.CreateContainerRequest]) (*connect.Response[v1.CreateContainerResponse], error)
	CheckImage(context.Context, *connect.Request[v1.CheckImageRequest]) (*connect.Response[v1.CheckImageResponse], error)
	CreateImage(context.Context, *connect.Request[v1.CreateImageRequest]) (*connect.Response[v1.CreateImageResponse], error)
	StartContainer(context.Context, *connect.Request[v1.StartContainerRequest]) (*connect.Response[v1.StartContainerResponse], error)
	StopContainer(context.Context, *connect.Request[v1.StopContainerRequest]) (*connect.Response[v1.StopContainerResponse], error)
	DeleteContainer(context.Context, *connect.Request[v1.DeleteContainerRequest]) (*connect.Response[v1.DeleteContainerResponse], error)
}

// NewPocketsServiceClient constructs a client for the shared.v1.PocketsService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPocketsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PocketsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	pocketsServiceMethods := v1.File_shared_v1_pockets_proto.Services().ByName("PocketsService").Methods()
	return &pocketsServiceClient{
		getContainers: connect.NewClient[v1.GetContainersRequest, v1.GetContainersResponse](
			httpClient,
			baseURL+PocketsServiceGetContainersProcedure,
			connect.WithSchema(pocketsServiceMethods.ByName("GetContainers")),
			connect.WithClientOptions(opts...),
		),
		createContainer: connect.NewClient[v1.CreateContainerRequest, v1.CreateContainerResponse](
			httpClient,
			baseURL+PocketsServiceCreateContainerProcedure,
			connect.WithSchema(pocketsServiceMethods.ByName("CreateContainer")),
			connect.WithClientOptions(opts...),
		),
		checkImage: connect.NewClient[v1.CheckImageRequest, v1.CheckImageResponse](
			httpClient,
			baseURL+PocketsServiceCheckImageProcedure,
			connect.WithSchema(pocketsServiceMethods.ByName("CheckImage")),
			connect.WithClientOptions(opts...),
		),
		createImage: connect.NewClient[v1.CreateImageRequest, v1.CreateImageResponse](
			httpClient,
			baseURL+PocketsServiceCreateImageProcedure,
			connect.WithSchema(pocketsServiceMethods.ByName("CreateImage")),
			connect.WithClientOptions(opts...),
		),
		startContainer: connect.NewClient[v1.StartContainerRequest, v1.StartContainerResponse](
			httpClient,
			baseURL+PocketsServiceStartContainerProcedure,
			connect.WithSchema(pocketsServiceMethods.ByName("StartContainer")),
			connect.WithClientOptions(opts...),
		),
		stopContainer: connect.NewClient[v1.StopContainerRequest, v1.StopContainerResponse](
			httpClient,
			baseURL+PocketsServiceStopContainerProcedure,
			connect.WithSchema(pocketsServiceMethods.ByName("StopContainer")),
			connect.WithClientOptions(opts...),
		),
		deleteContainer: connect.NewClient[v1.DeleteContainerRequest, v1.DeleteContainerResponse](
			httpClient,
			baseURL+PocketsServiceDeleteContainerProcedure,
			connect.WithSchema(pocketsServiceMethods.ByName("DeleteContainer")),
			connect.WithClientOptions(opts...),
		),
	}
}

// pocketsServiceClient implements PocketsServiceClient.
type pocketsServiceClient struct {
	getContainers   *connect.Client[v1.GetContainersRequest, v1.GetContainersResponse]
	createContainer *connect.Client[v1.CreateContainerRequest, v1.CreateContainerResponse]
	checkImage      *connect.Client[v1.CheckImageRequest, v1.CheckImageResponse]
	createImage     *connect.Client[v1.CreateImageRequest, v1.CreateImageResponse]
	startContainer  *connect.Client[v1.StartContainerRequest, v1.StartContainerResponse]
	stopContainer   *connect.Client[v1.StopContainerRequest, v1.StopContainerResponse]
	deleteContainer *connect.Client[v1.DeleteContainerRequest, v1.DeleteContainerResponse]
	getContainers *connect.Client[v1.GetContainersRequest, v1.GetContainersResponse]
}

// GetContainers calls shared.v1.PocketsService.GetContainers.
func (c *pocketsServiceClient) GetContainers(ctx context.Context, req *connect.Request[v1.GetContainersRequest]) (*connect.Response[v1.GetContainersResponse], error) {
	return c.getContainers.CallUnary(ctx, req)
}

// CreateContainer calls shared.v1.PocketsService.CreateContainer.
func (c *pocketsServiceClient) CreateContainer(ctx context.Context, req *connect.Request[v1.CreateContainerRequest]) (*connect.Response[v1.CreateContainerResponse], error) {
	return c.createContainer.CallUnary(ctx, req)
}

// CheckImage calls shared.v1.PocketsService.CheckImage.
func (c *pocketsServiceClient) CheckImage(ctx context.Context, req *connect.Request[v1.CheckImageRequest]) (*connect.Response[v1.CheckImageResponse], error) {
	return c.checkImage.CallUnary(ctx, req)
}

// CreateImage calls shared.v1.PocketsService.CreateImage.
func (c *pocketsServiceClient) CreateImage(ctx context.Context, req *connect.Request[v1.CreateImageRequest]) (*connect.Response[v1.CreateImageResponse], error) {
	return c.createImage.CallUnary(ctx, req)
}

// StartContainer calls shared.v1.PocketsService.StartContainer.
func (c *pocketsServiceClient) StartContainer(ctx context.Context, req *connect.Request[v1.StartContainerRequest]) (*connect.Response[v1.StartContainerResponse], error) {
	return c.startContainer.CallUnary(ctx, req)
}

// StopContainer calls shared.v1.PocketsService.StopContainer.
func (c *pocketsServiceClient) StopContainer(ctx context.Context, req *connect.Request[v1.StopContainerRequest]) (*connect.Response[v1.StopContainerResponse], error) {
	return c.stopContainer.CallUnary(ctx, req)
}

// DeleteContainer calls shared.v1.PocketsService.DeleteContainer.
func (c *pocketsServiceClient) DeleteContainer(ctx context.Context, req *connect.Request[v1.DeleteContainerRequest]) (*connect.Response[v1.DeleteContainerResponse], error) {
	return c.deleteContainer.CallUnary(ctx, req)
}

// PocketsServiceHandler is an implementation of the shared.v1.PocketsService service.
type PocketsServiceHandler interface {
	GetContainers(context.Context, *connect.Request[v1.GetContainersRequest]) (*connect.Response[v1.GetContainersResponse], error)
	CreateContainer(context.Context, *connect.Request[v1.CreateContainerRequest]) (*connect.Response[v1.CreateContainerResponse], error)
	CheckImage(context.Context, *connect.Request[v1.CheckImageRequest]) (*connect.Response[v1.CheckImageResponse], error)
	CreateImage(context.Context, *connect.Request[v1.CreateImageRequest]) (*connect.Response[v1.CreateImageResponse], error)
	StartContainer(context.Context, *connect.Request[v1.StartContainerRequest]) (*connect.Response[v1.StartContainerResponse], error)
	StopContainer(context.Context, *connect.Request[v1.StopContainerRequest]) (*connect.Response[v1.StopContainerResponse], error)
	DeleteContainer(context.Context, *connect.Request[v1.DeleteContainerRequest]) (*connect.Response[v1.DeleteContainerResponse], error)
// PocketsServiceHandler is an implementation of the shared.v1.PocketsService service.
type PocketsServiceHandler interface {
	GetContainers(context.Context, *connect.Request[v1.GetContainersRequest]) (*connect.Response[v1.GetContainersResponse], error)
}

// NewPocketsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPocketsServiceHandler(svc PocketsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	pocketsServiceMethods := v1.File_shared_v1_pockets_proto.Services().ByName("PocketsService").Methods()
	pocketsServiceGetContainersHandler := connect.NewUnaryHandler(
		PocketsServiceGetContainersProcedure,
		svc.GetContainers,
		connect.WithSchema(pocketsServiceMethods.ByName("GetContainers")),
		connect.WithHandlerOptions(opts...),
	)
	pocketsServiceCreateContainerHandler := connect.NewUnaryHandler(
		PocketsServiceCreateContainerProcedure,
		svc.CreateContainer,
		connect.WithSchema(pocketsServiceMethods.ByName("CreateContainer")),
		connect.WithHandlerOptions(opts...),
	)
	pocketsServiceCheckImageHandler := connect.NewUnaryHandler(
		PocketsServiceCheckImageProcedure,
		svc.CheckImage,
		connect.WithSchema(pocketsServiceMethods.ByName("CheckImage")),
		connect.WithHandlerOptions(opts...),
	)
	pocketsServiceCreateImageHandler := connect.NewUnaryHandler(
		PocketsServiceCreateImageProcedure,
		svc.CreateImage,
		connect.WithSchema(pocketsServiceMethods.ByName("CreateImage")),
		connect.WithHandlerOptions(opts...),
	)
	pocketsServiceStartContainerHandler := connect.NewUnaryHandler(
		PocketsServiceStartContainerProcedure,
		svc.StartContainer,
		connect.WithSchema(pocketsServiceMethods.ByName("StartContainer")),
		connect.WithHandlerOptions(opts...),
	)
	pocketsServiceStopContainerHandler := connect.NewUnaryHandler(
		PocketsServiceStopContainerProcedure,
		svc.StopContainer,
		connect.WithSchema(pocketsServiceMethods.ByName("StopContainer")),
		connect.WithHandlerOptions(opts...),
	)
	pocketsServiceDeleteContainerHandler := connect.NewUnaryHandler(
		PocketsServiceDeleteContainerProcedure,
		svc.DeleteContainer,
		connect.WithSchema(pocketsServiceMethods.ByName("DeleteContainer")),
		connect.WithHandlerOptions(opts...),
	)
	return "/shared.v1.PocketsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PocketsServiceGetContainersProcedure:
			pocketsServiceGetContainersHandler.ServeHTTP(w, r)
		case PocketsServiceCreateContainerProcedure:
			pocketsServiceCreateContainerHandler.ServeHTTP(w, r)
		case PocketsServiceCheckImageProcedure:
			pocketsServiceCheckImageHandler.ServeHTTP(w, r)
		case PocketsServiceCreateImageProcedure:
			pocketsServiceCreateImageHandler.ServeHTTP(w, r)
		case PocketsServiceStartContainerProcedure:
			pocketsServiceStartContainerHandler.ServeHTTP(w, r)
		case PocketsServiceStopContainerProcedure:
			pocketsServiceStopContainerHandler.ServeHTTP(w, r)
		case PocketsServiceDeleteContainerProcedure:
			pocketsServiceDeleteContainerHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPocketsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPocketsServiceHandler struct{}

func (UnimplementedPocketsServiceHandler) GetContainers(context.Context, *connect.Request[v1.GetContainersRequest]) (*connect.Response[v1.GetContainersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shared.v1.PocketsService.GetContainers is not implemented"))
}

func (UnimplementedPocketsServiceHandler) CreateContainer(context.Context, *connect.Request[v1.CreateContainerRequest]) (*connect.Response[v1.CreateContainerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shared.v1.PocketsService.CreateContainer is not implemented"))
}

func (UnimplementedPocketsServiceHandler) CheckImage(context.Context, *connect.Request[v1.CheckImageRequest]) (*connect.Response[v1.CheckImageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shared.v1.PocketsService.CheckImage is not implemented"))
}

func (UnimplementedPocketsServiceHandler) CreateImage(context.Context, *connect.Request[v1.CreateImageRequest]) (*connect.Response[v1.CreateImageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shared.v1.PocketsService.CreateImage is not implemented"))
}

func (UnimplementedPocketsServiceHandler) StartContainer(context.Context, *connect.Request[v1.StartContainerRequest]) (*connect.Response[v1.StartContainerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shared.v1.PocketsService.StartContainer is not implemented"))
}

func (UnimplementedPocketsServiceHandler) StopContainer(context.Context, *connect.Request[v1.StopContainerRequest]) (*connect.Response[v1.StopContainerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shared.v1.PocketsService.StopContainer is not implemented"))
}

func (UnimplementedPocketsServiceHandler) DeleteContainer(context.Context, *connect.Request[v1.DeleteContainerRequest]) (*connect.Response[v1.DeleteContainerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shared.v1.PocketsService.DeleteContainer is not implemented"))
}
