// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: shared/v1/pockets.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetContainersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainersRequest) Reset() {
	*x = GetContainersRequest{}
	mi := &file_shared_v1_pockets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainersRequest) ProtoMessage() {}

func (x *GetContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_pockets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainersRequest.ProtoReflect.Descriptor instead.
func (*GetContainersRequest) Descriptor() ([]byte, []int) {
	return file_shared_v1_pockets_proto_rawDescGZIP(), []int{0}
}

type GetContainersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*Container           `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainersResponse) Reset() {
	*x = GetContainersResponse{}
	mi := &file_shared_v1_pockets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainersResponse) ProtoMessage() {}

func (x *GetContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_pockets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainersResponse.ProtoReflect.Descriptor instead.
func (*GetContainersResponse) Descriptor() ([]byte, []int) {
	return file_shared_v1_pockets_proto_rawDescGZIP(), []int{1}
}

func (x *GetContainersResponse) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_shared_v1_pockets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_pockets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_shared_v1_pockets_proto_rawDescGZIP(), []int{2}
}

func (x *Container) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Container) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContainerRequest) Reset() {
	*x = CreateContainerRequest{}
	mi := &file_shared_v1_pockets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainerRequest) ProtoMessage() {}

func (x *CreateContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_pockets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainerRequest.ProtoReflect.Descriptor instead.
func (*CreateContainerRequest) Descriptor() ([]byte, []int) {
	return file_shared_v1_pockets_proto_rawDescGZIP(), []int{3}
}

func (x *CreateContainerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateContainerRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type CreateContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Container     *Container             `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContainerResponse) Reset() {
	*x = CreateContainerResponse{}
	mi := &file_shared_v1_pockets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainerResponse) ProtoMessage() {}

func (x *CreateContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_pockets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainerResponse.ProtoReflect.Descriptor instead.
func (*CreateContainerResponse) Descriptor() ([]byte, []int) {
	return file_shared_v1_pockets_proto_rawDescGZIP(), []int{4}
}

func (x *CreateContainerResponse) GetContainer() *Container {
	if x != nil {
		return x.Container
	}
	return nil
}

type CheckImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckImageRequest) Reset() {
	*x = CheckImageRequest{}
	mi := &file_shared_v1_pockets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckImageRequest) ProtoMessage() {}

func (x *CheckImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_pockets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckImageRequest.ProtoReflect.Descriptor instead.
func (*CheckImageRequest) Descriptor() ([]byte, []int) {
	return file_shared_v1_pockets_proto_rawDescGZIP(), []int{5}
}

func (x *CheckImageRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type CheckImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckImageResponse) Reset() {
	*x = CheckImageResponse{}
	mi := &file_shared_v1_pockets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckImageResponse) ProtoMessage() {}

func (x *CheckImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_pockets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckImageResponse.ProtoReflect.Descriptor instead.
func (*CheckImageResponse) Descriptor() ([]byte, []int) {
	return file_shared_v1_pockets_proto_rawDescGZIP(), []int{6}
}

func (x *CheckImageResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type CreateImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateImageRequest) Reset() {
	*x = CreateImageRequest{}
	mi := &file_shared_v1_pockets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateImageRequest) ProtoMessage() {}

func (x *CreateImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_pockets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateImageRequest.ProtoReflect.Descriptor instead.
func (*CreateImageRequest) Descriptor() ([]byte, []int) {
	return file_shared_v1_pockets_proto_rawDescGZIP(), []int{7}
}

func (x *CreateImageRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type CreateImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateImageResponse) Reset() {
	*x = CreateImageResponse{}
	mi := &file_shared_v1_pockets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateImageResponse) ProtoMessage() {}

func (x *CreateImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_pockets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateImageResponse.ProtoReflect.Descriptor instead.
func (*CreateImageResponse) Descriptor() ([]byte, []int) {
	return file_shared_v1_pockets_proto_rawDescGZIP(), []int{8}
}

type StartContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartContainerRequest) Reset() {
	*x = StartContainerRequest{}
	mi := &file_shared_v1_pockets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartContainerRequest) ProtoMessage() {}

func (x *StartContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_pockets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartContainerRequest.ProtoReflect.Descriptor instead.
func (*StartContainerRequest) Descriptor() ([]byte, []int) {
	return file_shared_v1_pockets_proto_rawDescGZIP(), []int{9}
}

func (x *StartContainerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StartContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartContainerResponse) Reset() {
	*x = StartContainerResponse{}
	mi := &file_shared_v1_pockets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartContainerResponse) ProtoMessage() {}

func (x *StartContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_pockets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartContainerResponse.ProtoReflect.Descriptor instead.
func (*StartContainerResponse) Descriptor() ([]byte, []int) {
	return file_shared_v1_pockets_proto_rawDescGZIP(), []int{10}
}

func (x *StartContainerResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type StopContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopContainerRequest) Reset() {
	*x = StopContainerRequest{}
	mi := &file_shared_v1_pockets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopContainerRequest) ProtoMessage() {}

func (x *StopContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_pockets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopContainerRequest.ProtoReflect.Descriptor instead.
func (*StopContainerRequest) Descriptor() ([]byte, []int) {
	return file_shared_v1_pockets_proto_rawDescGZIP(), []int{11}
}

func (x *StopContainerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StopContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopContainerResponse) Reset() {
	*x = StopContainerResponse{}
	mi := &file_shared_v1_pockets_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopContainerResponse) ProtoMessage() {}

func (x *StopContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_pockets_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopContainerResponse.ProtoReflect.Descriptor instead.
func (*StopContainerResponse) Descriptor() ([]byte, []int) {
	return file_shared_v1_pockets_proto_rawDescGZIP(), []int{12}
}

func (x *StopContainerResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type DeleteContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContainerRequest) Reset() {
	*x = DeleteContainerRequest{}
	mi := &file_shared_v1_pockets_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContainerRequest) ProtoMessage() {}

func (x *DeleteContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_pockets_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContainerRequest.ProtoReflect.Descriptor instead.
func (*DeleteContainerRequest) Descriptor() ([]byte, []int) {
	return file_shared_v1_pockets_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteContainerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContainerResponse) Reset() {
	*x = DeleteContainerResponse{}
	mi := &file_shared_v1_pockets_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContainerResponse) ProtoMessage() {}

func (x *DeleteContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_pockets_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContainerResponse.ProtoReflect.Descriptor instead.
func (*DeleteContainerResponse) Descriptor() ([]byte, []int) {
	return file_shared_v1_pockets_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteContainerResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_shared_v1_pockets_proto protoreflect.FileDescriptor

const file_shared_v1_pockets_proto_rawDesc = "" +
	"\n" +
	"\x17shared/v1/pockets.proto\x12\tshared.v1\"\x16\n" +
	"\x14GetContainersRequest\"M\n" +
	"\x15GetContainersResponse\x124\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x14.shared.v1.ContainerR\n" +
	"containers\"G\n" +
	"\tContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"F\n" +
	"\x16CreateContainerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"M\n" +
	"\x17CreateContainerResponse\x122\n" +
	"\tcontainer\x18\x01 \x01(\v2\x14.shared.v1.ContainerR\tcontainer\"-\n" +
	"\x11CheckImageRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\",\n" +
	"\x12CheckImageResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\".\n" +
	"\x12CreateImageRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\x15\n" +
	"\x13CreateImageResponse\"'\n" +
	"\x15StartContainerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x16StartContainerResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"&\n" +
	"\x14StopContainerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x15StopContainerResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"(\n" +
	"\x16DeleteContainerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x17DeleteContainerResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status2\xea\x04\n" +
	"\x0ePocketsService\x12T\n" +
	"\rGetContainers\x12\x1f.shared.v1.GetContainersRequest\x1a .shared.v1.GetContainersResponse\"\x00\x12Z\n" +
	"\x0fCreateContainer\x12!.shared.v1.CreateContainerRequest\x1a\".shared.v1.CreateContainerResponse\"\x00\x12K\n" +
	"\n" +
	"CheckImage\x12\x1c.shared.v1.CheckImageRequest\x1a\x1d.shared.v1.CheckImageResponse\"\x00\x12N\n" +
	"\vCreateImage\x12\x1d.shared.v1.CreateImageRequest\x1a\x1e.shared.v1.CreateImageResponse\"\x00\x12W\n" +
	"\x0eStartContainer\x12 .shared.v1.StartContainerRequest\x1a!.shared.v1.StartContainerResponse\"\x00\x12T\n" +
	"\rStopContainer\x12\x1f.shared.v1.StopContainerRequest\x1a .shared.v1.StopContainerResponse\"\x00\x12Z\n" +
	"\x0fDeleteContainer\x12!.shared.v1.DeleteContainerRequest\x1a\".shared.v1.DeleteContainerResponse\"\x00B/Z-github.com/matfire/pockets/shared/v1;sharedv1b\x06proto3"

var (
	file_shared_v1_pockets_proto_rawDescOnce sync.Once
	file_shared_v1_pockets_proto_rawDescData []byte
)

func file_shared_v1_pockets_proto_rawDescGZIP() []byte {
	file_shared_v1_pockets_proto_rawDescOnce.Do(func() {
		file_shared_v1_pockets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_v1_pockets_proto_rawDesc), len(file_shared_v1_pockets_proto_rawDesc)))
	})
	return file_shared_v1_pockets_proto_rawDescData
}

var file_shared_v1_pockets_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_shared_v1_pockets_proto_goTypes = []any{
	(*GetContainersRequest)(nil),    // 0: shared.v1.GetContainersRequest
	(*GetContainersResponse)(nil),   // 1: shared.v1.GetContainersResponse
	(*Container)(nil),               // 2: shared.v1.Container
	(*CreateContainerRequest)(nil),  // 3: shared.v1.CreateContainerRequest
	(*CreateContainerResponse)(nil), // 4: shared.v1.CreateContainerResponse
	(*CheckImageRequest)(nil),       // 5: shared.v1.CheckImageRequest
	(*CheckImageResponse)(nil),      // 6: shared.v1.CheckImageResponse
	(*CreateImageRequest)(nil),      // 7: shared.v1.CreateImageRequest
	(*CreateImageResponse)(nil),     // 8: shared.v1.CreateImageResponse
	(*StartContainerRequest)(nil),   // 9: shared.v1.StartContainerRequest
	(*StartContainerResponse)(nil),  // 10: shared.v1.StartContainerResponse
	(*StopContainerRequest)(nil),    // 11: shared.v1.StopContainerRequest
	(*StopContainerResponse)(nil),   // 12: shared.v1.StopContainerResponse
	(*DeleteContainerRequest)(nil),  // 13: shared.v1.DeleteContainerRequest
	(*DeleteContainerResponse)(nil), // 14: shared.v1.DeleteContainerResponse
}
var file_shared_v1_pockets_proto_depIdxs = []int32{
	2,  // 0: shared.v1.GetContainersResponse.containers:type_name -> shared.v1.Container
	2,  // 1: shared.v1.CreateContainerResponse.container:type_name -> shared.v1.Container
	0,  // 2: shared.v1.PocketsService.GetContainers:input_type -> shared.v1.GetContainersRequest
	3,  // 3: shared.v1.PocketsService.CreateContainer:input_type -> shared.v1.CreateContainerRequest
	5,  // 4: shared.v1.PocketsService.CheckImage:input_type -> shared.v1.CheckImageRequest
	7,  // 5: shared.v1.PocketsService.CreateImage:input_type -> shared.v1.CreateImageRequest
	9,  // 6: shared.v1.PocketsService.StartContainer:input_type -> shared.v1.StartContainerRequest
	11, // 7: shared.v1.PocketsService.StopContainer:input_type -> shared.v1.StopContainerRequest
	13, // 8: shared.v1.PocketsService.DeleteContainer:input_type -> shared.v1.DeleteContainerRequest
	1,  // 9: shared.v1.PocketsService.GetContainers:output_type -> shared.v1.GetContainersResponse
	4,  // 10: shared.v1.PocketsService.CreateContainer:output_type -> shared.v1.CreateContainerResponse
	6,  // 11: shared.v1.PocketsService.CheckImage:output_type -> shared.v1.CheckImageResponse
	8,  // 12: shared.v1.PocketsService.CreateImage:output_type -> shared.v1.CreateImageResponse
	10, // 13: shared.v1.PocketsService.StartContainer:output_type -> shared.v1.StartContainerResponse
	12, // 14: shared.v1.PocketsService.StopContainer:output_type -> shared.v1.StopContainerResponse
	14, // 15: shared.v1.PocketsService.DeleteContainer:output_type -> shared.v1.DeleteContainerResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_shared_v1_pockets_proto_init() }
func file_shared_v1_pockets_proto_init() {
	if File_shared_v1_pockets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_v1_pockets_proto_rawDesc), len(file_shared_v1_pockets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_v1_pockets_proto_goTypes,
		DependencyIndexes: file_shared_v1_pockets_proto_depIdxs,
		MessageInfos:      file_shared_v1_pockets_proto_msgTypes,
	}.Build()
	File_shared_v1_pockets_proto = out.File
	file_shared_v1_pockets_proto_goTypes = nil
	file_shared_v1_pockets_proto_depIdxs = nil
}
