// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file shared/v1/pockets.proto (package shared.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file shared/v1/pockets.proto.
 */
export const file_shared_v1_pockets: GenFile = /*@__PURE__*/
  fileDesc("ChdzaGFyZWQvdjEvcG9ja2V0cy5wcm90bxIJc2hhcmVkLnYxIhYKFEdldENvbnRhaW5lcnNSZXF1ZXN0IkEKFUdldENvbnRhaW5lcnNSZXNwb25zZRIoCgpjb250YWluZXJzGAEgAygLMhQuc2hhcmVkLnYxLkNvbnRhaW5lciI1CglDb250YWluZXISCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRIOCgZzdGF0dXMYAyABKAkiNwoWQ3JlYXRlQ29udGFpbmVyUmVxdWVzdBIMCgRuYW1lGAEgASgJEg8KB3ZlcnNpb24YAiABKAkiQgoXQ3JlYXRlQ29udGFpbmVyUmVzcG9uc2USJwoJY29udGFpbmVyGAEgASgLMhQuc2hhcmVkLnYxLkNvbnRhaW5lciIkChFDaGVja0ltYWdlUmVxdWVzdBIPCgd2ZXJzaW9uGAEgASgJIiQKEkNoZWNrSW1hZ2VSZXNwb25zZRIOCgZleGlzdHMYASABKAgiJQoSQ3JlYXRlSW1hZ2VSZXF1ZXN0Eg8KB3ZlcnNpb24YASABKAkiFQoTQ3JlYXRlSW1hZ2VSZXNwb25zZSIjChVTdGFydENvbnRhaW5lclJlcXVlc3QSCgoCaWQYASABKAkiKAoWU3RhcnRDb250YWluZXJSZXNwb25zZRIOCgZzdGF0dXMYASABKAgiIgoUU3RvcENvbnRhaW5lclJlcXVlc3QSCgoCaWQYASABKAkiJwoVU3RvcENvbnRhaW5lclJlc3BvbnNlEg4KBnN0YXR1cxgBIAEoCCIkChZEZWxldGVDb250YWluZXJSZXF1ZXN0EgoKAmlkGAEgASgJIikKF0RlbGV0ZUNvbnRhaW5lclJlc3BvbnNlEg4KBnN0YXR1cxgBIAEoCDLqBAoOUG9ja2V0c1NlcnZpY2USVAoNR2V0Q29udGFpbmVycxIfLnNoYXJlZC52MS5HZXRDb250YWluZXJzUmVxdWVzdBogLnNoYXJlZC52MS5HZXRDb250YWluZXJzUmVzcG9uc2UiABJaCg9DcmVhdGVDb250YWluZXISIS5zaGFyZWQudjEuQ3JlYXRlQ29udGFpbmVyUmVxdWVzdBoiLnNoYXJlZC52MS5DcmVhdGVDb250YWluZXJSZXNwb25zZSIAEksKCkNoZWNrSW1hZ2USHC5zaGFyZWQudjEuQ2hlY2tJbWFnZVJlcXVlc3QaHS5zaGFyZWQudjEuQ2hlY2tJbWFnZVJlc3BvbnNlIgASTgoLQ3JlYXRlSW1hZ2USHS5zaGFyZWQudjEuQ3JlYXRlSW1hZ2VSZXF1ZXN0Gh4uc2hhcmVkLnYxLkNyZWF0ZUltYWdlUmVzcG9uc2UiABJXCg5TdGFydENvbnRhaW5lchIgLnNoYXJlZC52MS5TdGFydENvbnRhaW5lclJlcXVlc3QaIS5zaGFyZWQudjEuU3RhcnRDb250YWluZXJSZXNwb25zZSIAElQKDVN0b3BDb250YWluZXISHy5zaGFyZWQudjEuU3RvcENvbnRhaW5lclJlcXVlc3QaIC5zaGFyZWQudjEuU3RvcENvbnRhaW5lclJlc3BvbnNlIgASWgoPRGVsZXRlQ29udGFpbmVyEiEuc2hhcmVkLnYxLkRlbGV0ZUNvbnRhaW5lclJlcXVlc3QaIi5zaGFyZWQudjEuRGVsZXRlQ29udGFpbmVyUmVzcG9uc2UiAEIvWi1naXRodWIuY29tL21hdGZpcmUvcG9ja2V0cy9zaGFyZWQvdjE7c2hhcmVkdjFiBnByb3RvMw");

/**
 * @generated from message shared.v1.GetContainersRequest
 */
export type GetContainersRequest = Message<"shared.v1.GetContainersRequest"> & {
};

/**
 * Describes the message shared.v1.GetContainersRequest.
 * Use `create(GetContainersRequestSchema)` to create a new message.
 */
export const GetContainersRequestSchema: GenMessage<GetContainersRequest> = /*@__PURE__*/
  messageDesc(file_shared_v1_pockets, 0);

/**
 * @generated from message shared.v1.GetContainersResponse
 */
export type GetContainersResponse = Message<"shared.v1.GetContainersResponse"> & {
  /**
   * @generated from field: repeated shared.v1.Container containers = 1;
   */
  containers: Container[];
};

/**
 * Describes the message shared.v1.GetContainersResponse.
 * Use `create(GetContainersResponseSchema)` to create a new message.
 */
export const GetContainersResponseSchema: GenMessage<GetContainersResponse> = /*@__PURE__*/
  messageDesc(file_shared_v1_pockets, 1);

/**
 * @generated from message shared.v1.Container
 */
export type Container = Message<"shared.v1.Container"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string status = 3;
   */
  status: string;
};

/**
 * Describes the message shared.v1.Container.
 * Use `create(ContainerSchema)` to create a new message.
 */
export const ContainerSchema: GenMessage<Container> = /*@__PURE__*/
  messageDesc(file_shared_v1_pockets, 2);

/**
 * @generated from message shared.v1.CreateContainerRequest
 */
export type CreateContainerRequest = Message<"shared.v1.CreateContainerRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string version = 2;
   */
  version: string;
};

/**
 * Describes the message shared.v1.CreateContainerRequest.
 * Use `create(CreateContainerRequestSchema)` to create a new message.
 */
export const CreateContainerRequestSchema: GenMessage<CreateContainerRequest> = /*@__PURE__*/
  messageDesc(file_shared_v1_pockets, 3);

/**
 * @generated from message shared.v1.CreateContainerResponse
 */
export type CreateContainerResponse = Message<"shared.v1.CreateContainerResponse"> & {
  /**
   * @generated from field: shared.v1.Container container = 1;
   */
  container?: Container;
};

/**
 * Describes the message shared.v1.CreateContainerResponse.
 * Use `create(CreateContainerResponseSchema)` to create a new message.
 */
export const CreateContainerResponseSchema: GenMessage<CreateContainerResponse> = /*@__PURE__*/
  messageDesc(file_shared_v1_pockets, 4);

/**
 * @generated from message shared.v1.CheckImageRequest
 */
export type CheckImageRequest = Message<"shared.v1.CheckImageRequest"> & {
  /**
   * @generated from field: string version = 1;
   */
  version: string;
};

/**
 * Describes the message shared.v1.CheckImageRequest.
 * Use `create(CheckImageRequestSchema)` to create a new message.
 */
export const CheckImageRequestSchema: GenMessage<CheckImageRequest> = /*@__PURE__*/
  messageDesc(file_shared_v1_pockets, 5);

/**
 * @generated from message shared.v1.CheckImageResponse
 */
export type CheckImageResponse = Message<"shared.v1.CheckImageResponse"> & {
  /**
   * @generated from field: bool exists = 1;
   */
  exists: boolean;
};

/**
 * Describes the message shared.v1.CheckImageResponse.
 * Use `create(CheckImageResponseSchema)` to create a new message.
 */
export const CheckImageResponseSchema: GenMessage<CheckImageResponse> = /*@__PURE__*/
  messageDesc(file_shared_v1_pockets, 6);

/**
 * @generated from message shared.v1.CreateImageRequest
 */
export type CreateImageRequest = Message<"shared.v1.CreateImageRequest"> & {
  /**
   * @generated from field: string version = 1;
   */
  version: string;
};

/**
 * Describes the message shared.v1.CreateImageRequest.
 * Use `create(CreateImageRequestSchema)` to create a new message.
 */
export const CreateImageRequestSchema: GenMessage<CreateImageRequest> = /*@__PURE__*/
  messageDesc(file_shared_v1_pockets, 7);

/**
 * @generated from message shared.v1.CreateImageResponse
 */
export type CreateImageResponse = Message<"shared.v1.CreateImageResponse"> & {
};

/**
 * Describes the message shared.v1.CreateImageResponse.
 * Use `create(CreateImageResponseSchema)` to create a new message.
 */
export const CreateImageResponseSchema: GenMessage<CreateImageResponse> = /*@__PURE__*/
  messageDesc(file_shared_v1_pockets, 8);

/**
 * @generated from message shared.v1.StartContainerRequest
 */
export type StartContainerRequest = Message<"shared.v1.StartContainerRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message shared.v1.StartContainerRequest.
 * Use `create(StartContainerRequestSchema)` to create a new message.
 */
export const StartContainerRequestSchema: GenMessage<StartContainerRequest> = /*@__PURE__*/
  messageDesc(file_shared_v1_pockets, 9);

/**
 * @generated from message shared.v1.StartContainerResponse
 */
export type StartContainerResponse = Message<"shared.v1.StartContainerResponse"> & {
  /**
   * @generated from field: bool status = 1;
   */
  status: boolean;
};

/**
 * Describes the message shared.v1.StartContainerResponse.
 * Use `create(StartContainerResponseSchema)` to create a new message.
 */
export const StartContainerResponseSchema: GenMessage<StartContainerResponse> = /*@__PURE__*/
  messageDesc(file_shared_v1_pockets, 10);

/**
 * @generated from message shared.v1.StopContainerRequest
 */
export type StopContainerRequest = Message<"shared.v1.StopContainerRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message shared.v1.StopContainerRequest.
 * Use `create(StopContainerRequestSchema)` to create a new message.
 */
export const StopContainerRequestSchema: GenMessage<StopContainerRequest> = /*@__PURE__*/
  messageDesc(file_shared_v1_pockets, 11);

/**
 * @generated from message shared.v1.StopContainerResponse
 */
export type StopContainerResponse = Message<"shared.v1.StopContainerResponse"> & {
  /**
   * @generated from field: bool status = 1;
   */
  status: boolean;
};

/**
 * Describes the message shared.v1.StopContainerResponse.
 * Use `create(StopContainerResponseSchema)` to create a new message.
 */
export const StopContainerResponseSchema: GenMessage<StopContainerResponse> = /*@__PURE__*/
  messageDesc(file_shared_v1_pockets, 12);

/**
 * @generated from message shared.v1.DeleteContainerRequest
 */
export type DeleteContainerRequest = Message<"shared.v1.DeleteContainerRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message shared.v1.DeleteContainerRequest.
 * Use `create(DeleteContainerRequestSchema)` to create a new message.
 */
export const DeleteContainerRequestSchema: GenMessage<DeleteContainerRequest> = /*@__PURE__*/
  messageDesc(file_shared_v1_pockets, 13);

/**
 * @generated from message shared.v1.DeleteContainerResponse
 */
export type DeleteContainerResponse = Message<"shared.v1.DeleteContainerResponse"> & {
  /**
   * @generated from field: bool status = 1;
   */
  status: boolean;
};

/**
 * Describes the message shared.v1.DeleteContainerResponse.
 * Use `create(DeleteContainerResponseSchema)` to create a new message.
 */
export const DeleteContainerResponseSchema: GenMessage<DeleteContainerResponse> = /*@__PURE__*/
  messageDesc(file_shared_v1_pockets, 14);

/**
 * @generated from service shared.v1.PocketsService
 */
export const PocketsService: GenService<{
  /**
   * @generated from rpc shared.v1.PocketsService.GetContainers
   */
  getContainers: {
    methodKind: "unary";
    input: typeof GetContainersRequestSchema;
    output: typeof GetContainersResponseSchema;
  },
  /**
   * @generated from rpc shared.v1.PocketsService.CreateContainer
   */
  createContainer: {
    methodKind: "unary";
    input: typeof CreateContainerRequestSchema;
    output: typeof CreateContainerResponseSchema;
  },
  /**
   * @generated from rpc shared.v1.PocketsService.CheckImage
   */
  checkImage: {
    methodKind: "unary";
    input: typeof CheckImageRequestSchema;
    output: typeof CheckImageResponseSchema;
  },
  /**
   * @generated from rpc shared.v1.PocketsService.CreateImage
   */
  createImage: {
    methodKind: "unary";
    input: typeof CreateImageRequestSchema;
    output: typeof CreateImageResponseSchema;
  },
  /**
   * @generated from rpc shared.v1.PocketsService.StartContainer
   */
  startContainer: {
    methodKind: "unary";
    input: typeof StartContainerRequestSchema;
    output: typeof StartContainerResponseSchema;
  },
  /**
   * @generated from rpc shared.v1.PocketsService.StopContainer
   */
  stopContainer: {
    methodKind: "unary";
    input: typeof StopContainerRequestSchema;
    output: typeof StopContainerResponseSchema;
  },
  /**
   * @generated from rpc shared.v1.PocketsService.DeleteContainer
   */
  deleteContainer: {
    methodKind: "unary";
    input: typeof DeleteContainerRequestSchema;
    output: typeof DeleteContainerResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_shared_v1_pockets, 0);

