name: release
on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: install buf
        run: go install github.com/bufbuild/buf/cmd/buf@latest
      - name: install protoc-gen-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - name: install protoc-gen-connect-go
        run: go install connectrpc.com/connect/cmd/protoc-gen-connect-go@latest
      - name: install grpcurl
        run: go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
      - name: generate proto
        run: make build/proto
      - name: run goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
